DbdHost=localhost
AuthType=auth/none
PidFile=/home/slurm/work/tutorials/user_scaling/var/slurmdbd.pid
LogFile=/home/slurm/work/tutorials/user_scaling/log/slurmdbd.log
StorageHost=localhost
StorageUser=slurm
StoragePass=slurm
SlurmUser=slurm
StorageLoc=slurmdb_user_scaling
